FROM python:3.11-slim

WORKDIR /app

ENV PIP_INDEX_URL=https://pypi.org/simple
ENV PIP_NO_CACHE_DIR=1

COPY requirements.pypi.txt requirements.txt

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY app/ app/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
